haimtran 12/12/2023

let build chatgpt by andrej kaparthy 

part 1 

In [1]:
# !wget https://raw.g ithubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

In [2]:
import torch

In [3]:
batch_size = 64 # how many independent sequences will we process in parallel 
block_size = 256  # what is the maximum context length for predictions?
max_iters = 5000 
eval_interval = 500 
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200 

n_embed = 384 
n_head = 6 
n_layer = 6 
dropout = 0.2

torch.manual_seed(1337) 


# batch_size = 32 # how many independent sequences will we process in parallel 
# block_size = 8  # what is the maximum context length for predictions?
# max_iters = 3000 
# eval_interval = 300 
# learning_rate = 1e-2
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# eval_iters = 200 
# n_embed = 32 
# torch.manual_seed(1337) 

In [4]:
# device = "cuda" if torch.cuda.is_available() else "cpu"

In [5]:
torch.set_default_device(device)

read input text 

In [6]:
with open("input.txt", 'r', encoding='utf-8') as f:
  text = f.read()

In [7]:
# print(text[:1000])

In [8]:
len(text)

1115394

In [9]:
chars = sorted(list(set(text)))
vocab_size =len(chars)
print('.'.join(chars))
print(vocab_size)


. .!.$.&.'.,.-...3.:.;.?.A.B.C.D.E.F.G.H.I.J.K.L.M.N.O.P.Q.R.S.T.U.V.W.X.Y.Z.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z
65


In [10]:
len(chars)

65

build string to index map, encode and decode 

In [11]:
stoi = { ch:i for i,ch in enumerate(chars)}
itos = { i:ch for i,ch in enumerate(chars)}

In [12]:
encode = lambda s: [stoi[c] for c in s] # encode take a string and output list of integer

In [13]:
decode = lambda l: ''.join([itos[i] for i in l]) # decode a list of integer to a string 

In [14]:
print(encode('hello there'))

[46, 43, 50, 50, 53, 1, 58, 46, 43, 56, 43]


In [15]:
print(decode(encode('hello there')))

hello there


In [16]:
data = torch.tensor(encode(text))

In [17]:
print(data.shape, data.type)
# print(data[:1000])

torch.Size([1115394]) <built-in method type of Tensor object at 0x7f08d1ee71a0>


In [18]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[:n]

In [19]:
# context length
# block_size = 8 
train_data[:block_size + 1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
        47, 59, 57,  1, 47, 57,  1, 41, 

In [20]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

In [21]:
# for t in range(block_size):
#   context = x[:t+1]
#   target = y[t]
#   print(f"when input is {context} target is {target}")

In [22]:
torch.manual_seed(1337)
# batch_size = 4
# block_size = 8 

In [23]:
def get_batch(split):
  # generate a small batch of data of input x and targets y 
  data = train_data if split == 'train' else val_data 
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([ data[i:i+block_size] for i in ix])
  y = torch.stack([ data[i+1: i+block_size+1] for i in ix])
  x,y = x.to(device), y.to(device)
  return x, y 

In [24]:
x,y = get_batch('train')

In [25]:
# x

In [26]:
# y

In [27]:
# batch_size = 32 # how many independent sequences will we process in parallel 
# block_size = 8  # what is the maximum context length for predictions?
# max_iters = 5000 
# eval_interval = 500 
# learning_rate = 1e-3 
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# eval_iters = 200 
# n_embed = 32 

In [28]:
import torch.nn as nn 
from torch.nn import functional as F 

In [29]:
class Head(nn.Module):
  
  def __init__(self, head_size) -> None:
    super().__init__()
    self.key = nn.Linear(n_embed, head_size, bias=False)
    self.query = nn.Linear(n_embed, head_size, bias=False)
    self.value = nn.Linear(n_embed,  head_size, bias=False)
    self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

    self.dropout = nn.Dropout(dropout)
    
  def forward(self, x):
    B,T,C = x.shape 
    k = self.key(x)   # (B, T, C)
    q = self.query(x) # (B, T, C)
    # compute attention scores ("affinities")
    wei = q @ k.transpose(-2,-1) * C**-0.05 # (B, T, C) @ (B, C, T) -> (B, T, T)
    wei = wei.masked_fill(self.tril[:T,:T] == 0, float('-inf')) # (B, T, T)
    wei = F.softmax(wei, dim=-1) # (B, T, T)
    wei = self.dropout(wei)
    # perform the weighted aggregation of the values 
    v = self.value(x) # (B, T, C)
    out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
    return out 
  

class FeedForward(nn.Module):

  def __init__(self, n_embed) -> None:
    super().__init__()
    self.net = nn.Sequential(
      nn.Linear(n_embed, 4 * n_embed),
      nn.ReLU(),
      nn.Linear(4 * n_embed, n_embed),
      nn.Dropout(dropout)
    )

  def forward(self, x):
    return self.net(x)

class MultiHeadAttention(nn.Module):

  def __init__(self, num_heads, head_size) -> None:
    super().__init__()
    self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
    self.proj = nn.Linear(n_embed, n_embed)
    self.dropout = nn.Dropout(dropout)

  def forward(self, x):
    out = torch.cat([h(x) for h in self.heads], dim=-1)
    out = self.dropout(self.proj(out))
    return out 
  

class Block(nn.Module):

  def __init__(self, n_embed, n_head) -> None:
    super().__init__()
    head_size = n_embed // n_head
    self.sa = MultiHeadAttention(n_head, head_size)
    self.ffwd = FeedForward(n_embed)
    self.ln1 = nn.LayerNorm(n_embed)
    self.ln2 = nn.LayerNorm(n_embed)

  def forward(self, x):
    x = x + self.sa(self.ln1(x))
    x = x + self.ffwd(self.ln2(x))
    return x 


class BigramLanguageMmodel(nn.Module):

  def __init__(self, vocab_size) -> None:
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, n_embed)
    self.position_embedding_talbe = nn.Embedding(block_size, n_embed)
    self.blocks = nn.Sequential(*[Block(n_embed, n_head=n_head) for _ in range(n_layer)])
    self.ln_f = nn.LayerNorm(n_embed) # final layer norm 
    self.lm_head = nn.Linear(n_embed, vocab_size)

  def forward(self, idx, targets=None):
    B, T = idx.shape 
    
    # idx and targets are both (B, T) tensor of integers 
    tok_emb = self.token_embedding_table(idx) # (B, T, C)
    pos_emb = self.position_embedding_talbe(torch.arange(T, device=device))
    x = tok_emb + pos_emb # (B, T, C)
    x = self.blocks(x) # (B, T, C) 
    x = self.ln_f(x) # (B, T, C)  
    logits = self.lm_head(x) # (B, T, vocab_size)

    if targets is None:
      loss = None 
    else: 
      B, T, C = logits.shape 
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      # softmax and loss
      loss = F.cross_entropy(logits, targets)

    return logits, loss 
  

  def generate(self, idx, max_new_tokens):
    # idx is (B, T) array of indicies in the current context 
    for _ in range(max_new_tokens):
      # crop ind to the last block_size tokens 
      idx_cond = idx[:, -block_size:]
      # get the predictions
      logits, loss = self(idx_cond)
      # focus only on the last time step 
      logits = logits[:, -1, :] # become (B, C)
      # apply softmax to get probablities 
      probs = F.softmax(logits, dim=-1) # (B, C)
      # sample from the distribution
      idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
      # append sampled index to the running sequence
      idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
    return idx

In [30]:
model = BigramLanguageMmodel(vocab_size)
model = model.to(device)

pytorch optimizer 

In [31]:
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

In [32]:
@torch.no_grad()
def estimate_loss():
  out = {}
  model.eval()
  for split in ['train', 'val']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X, Y = get_batch(split)
      logits, loss = model(X, Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  model.train()
  return out 

In [33]:
# batch_size = 32 
for iter in range(max_iters):

  # every once in a while evaluate the loss on the train and val sets 
  if iter % eval_interval == 0:
    losses = estimate_loss()
    print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

  # sample a batch of data 
  xb, yb = get_batch("train")
  
  # evaluate the loss 
  logits, loss = model(xb, yb)
  # optimizer step 
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

step 0: train loss 4.4150, val loss 4.4153
step 500: train loss 1.8101, val loss 1.8081
step 1000: train loss 1.5178, val loss 1.5173
step 1500: train loss 1.3882, val loss 1.3886
step 2000: train loss 1.3077, val loss 1.3067
step 2500: train loss 1.2566, val loss 1.2569
step 3000: train loss 1.2125, val loss 1.2117
step 3500: train loss 1.1730, val loss 1.1734
step 4000: train loss 1.1388, val loss 1.1392
step 4500: train loss 1.1071, val loss 1.1066


In [34]:
print(decode(model.generate(idx=torch.zeros((1,1), dtype=torch.long, device=device), max_new_tokens=500)[0].tolist()))


YORK:
You, friends, pardon, my loving speech marks,
Did not anot hear.

STANLEY:
But, my lord; 'tis not thinks.
What's on your hand; 'dness e'er in your great me.

LOVER:
Thrive being out an either broke.

HASTINGS:
Marry, let hear i have these cause on him
Against his business.

MARCIUS:
O farewell the pedlick,
I will pity the gives of Magid firm our self.

MARCIUS:
Well, how shall wear his househind exposters fore
World' Inquirt-reason; therein Coxio; here's Saint.

CORIOLANUS:
I know he did, 


In [35]:
x.device

device(type='cuda', index=0)

 self-attention 

In [36]:
torch.manual_seed(1337)

In [37]:
B,T,C = 4,8,2 # batch, time, channel
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

In [38]:
# we want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
  for t in range(T):
    xprev = x[b,:t+1] # (t,C)
    xbow[b,t] = torch.mean(xprev,0)

In [39]:
x[0,:,:]

tensor([[-0.2143, -0.5001],
        [ 0.4922,  1.2006],
        [-0.8338, -0.8490],
        [-0.7448,  1.7622],
        [-0.7925, -1.1531],
        [ 1.6754,  0.2774],
        [ 0.1732, -0.1147],
        [-1.1392,  0.3428]], device='cuda:0')

In [40]:
xbow[0,:,:]

tensor([[-0.2143, -0.5001],
        [ 0.1390,  0.3503],
        [-0.1853, -0.0495],
        [-0.3252,  0.4034],
        [-0.4186,  0.0921],
        [-0.0696,  0.1230],
        [-0.0349,  0.0891],
        [-0.1730,  0.1208]], device='cuda:0')

In [41]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b 
print('a=')
print(a)
print('b=')
print(b)
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]], device='cuda:0')
b=
tensor([[3., 9.],
        [8., 0.],
        [3., 7.]], device='cuda:0')
c=
tensor([[3.0000, 9.0000],
        [5.5000, 4.5000],
        [4.6667, 5.3333]], device='cuda:0')


In [42]:
# keep dim and broadcast 
a / torch.sum(a, 1, keepdim=True)

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]], device='cuda:0')

In [43]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
wei 

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]],
       device='cuda:0')

In [44]:
xbow2 = wei @ x # (B, T, T) @ (B, T, C) -----> (B, T, C)

In [45]:
torch.allclose(xbow, xbow2)

True

version 3 

In [46]:
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))

In [47]:
wei = wei.masked_fill(tril == 0, float('-inf'))

In [48]:
wei = F.softmax(wei, dim=-1)

In [49]:
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]],
       device='cuda:0')

In [50]:
xbow3 = wei @ x 

In [51]:
torch.allclose(xbow, xbow3)

True

In [52]:
# version 4: selft-attention 
torch.manual_seed(1337)
B, T, C = 4,8,32
x = torch.randn(B,T,C)

In [53]:
# let's see a single Head perform self-attention 
head_size = 16 
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

In [54]:
k = key(x) # (B, T, 16)
q = query(x) # (B, T, 16)
wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) -> (B, T, T)

In [55]:
tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)

In [56]:
v = value(x)
out = wei @ v  

In [57]:
out.shape

torch.Size([4, 8, 16])